# Generated by Django 2.1.2 on 2018-11-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidataget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='article_image',
            new_name='saved',
        ),
        migrations.RemoveField(
            model_name='save',
            name='article_description',
        ),
        migrations.RemoveField(
            model_name='save',
            name='article_time',
        ),
        migrations.RemoveField(
            model_name='save',
            name='article_title',
        ),
        migrations.RemoveField(
            model_name='save',
            name='article_url',
        ),
    ]
