# Generated by Django 2.1.2 on 2018-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidataget', '0002_auto_20181104_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='article_description',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='article_image',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='article_time',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='article_url',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
