# Generated by Django 2.1.2 on 2018-11-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidataget', '0004_auto_20181104_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='article_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
