# Generated by Django 2.1.2 on 2018-11-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidataget', '0003_auto_20181104_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='saved',
            new_name='article_title',
        ),
    ]
